/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSkillsRouteImport } from './routes/_layout/skills'
import { Route as LayoutExperienceRouteImport } from './routes/_layout/experience'
import { Route as LayoutBlogRouteImport } from './routes/_layout/blog'
import { Route as LayoutProjectsProjectIdRouteImport } from './routes/_layout/projects.$projectId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSkillsRoute = LayoutSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExperienceRoute = LayoutExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlogRoute = LayoutBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsProjectIdRoute = LayoutProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/blog': typeof LayoutBlogRoute
  '/experience': typeof LayoutExperienceRoute
  '/skills': typeof LayoutSkillsRoute
  '/': typeof LayoutIndexRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/blog': typeof LayoutBlogRoute
  '/experience': typeof LayoutExperienceRoute
  '/skills': typeof LayoutSkillsRoute
  '/': typeof LayoutIndexRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/blog': typeof LayoutBlogRoute
  '/_layout/experience': typeof LayoutExperienceRoute
  '/_layout/skills': typeof LayoutSkillsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/projects/$projectId': typeof LayoutProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/blog' | '/experience' | '/skills' | '/' | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/blog' | '/experience' | '/skills' | '/' | '/projects/$projectId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/blog'
    | '/_layout/experience'
    | '/_layout/skills'
    | '/_layout/'
    | '/_layout/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/skills': {
      id: '/_layout/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof LayoutSkillsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/experience': {
      id: '/_layout/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof LayoutExperienceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blog': {
      id: '/_layout/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof LayoutBlogRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId': {
      id: '/_layout/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof LayoutProjectsProjectIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBlogRoute: typeof LayoutBlogRoute
  LayoutExperienceRoute: typeof LayoutExperienceRoute
  LayoutSkillsRoute: typeof LayoutSkillsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProjectsProjectIdRoute: typeof LayoutProjectsProjectIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBlogRoute: LayoutBlogRoute,
  LayoutExperienceRoute: LayoutExperienceRoute,
  LayoutSkillsRoute: LayoutSkillsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProjectsProjectIdRoute: LayoutProjectsProjectIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
